### ISSUE TITLE
Cors issues

### ISSUE THREAD

**Issue by James-E-Adams** [procore-oss/js-sdk#24]
G'day!

I'm running into some cors issues using the implicit grant flow described in the docs to talk to the procore api from a SPA client. 

I've got the auth going fine, but when I make a request (say to projects) via `procore.get(projects(..))`,

I get the following 

```
Failed to load https://sandbox.procore.com/vapid/projects: Response to preflight request doesn't pass 
access control check: The value of the 'Access-Control-Allow-Credentials' header in the response is '' 
which must be 'true' when the request's credentials mode is 'include'. Origin 'http://localhost' is 
therefore not allowed access.
```
It is the same on the sandbox and the production api.
It fails on the preflight and doesn't make the actual request.
Is there another header I must include? From what I can tell, it's expecting the response from procore to contain `'Access-Control-Allow-Credentials' : true` in the headers.

It works fine with web security disabled as a runtime flag for chrome.

**Comment by senorflor** [comment]
@James-E-Adams of 2018: hello from the future! (And hello everyone else too.)

I just dealt with this same issue integrating with the Procore API for the first time today. The trick is to set the `credentials` mode of requests that the client issues to `omit` instead of its default value, `include` (c.f. https://github.com/procore/js-sdk/blob/90304538e483705fd799803761efef3c342dd328/lib/client.ts#L44), since the Procore API server doesn't set the response header mentioned in the error. Passing the bearer token in the `Authorization` header, as the OAuth `Authorizer` does by default (c.f. https://github.com/procore/js-sdk/blob/90304538e483705fd799803761efef3c342dd328/lib/oauth.ts#L9), doesn't seem to be affected by the `omit` setting.

It is a little tricky that the default in https://github.com/procore/js-sdk#implicit-grant-flow doesn't seem to work in the browser, at least in the iframe embedded app I am building. Maybe this is worth a change to the default or some additional documentation, @bravely or @dancingshell ? (Just popped the two most recent contributors to the client off the git history 😄)
